reactabular/reactabular

- __tests__/predicates/infix-test.js
- __tests__/predicates/prefix-test.js
- __tests__/search-test.js
- lib/index.js
- lib/predicates/index.js
- lib/predicates/infix.js
- lib/predicates/prefix.js
- lib/search.jsx
Search is just a special case of filtering. I kept the default search to be prefix. I'm planning on adding some search highlighting and then switching it to infix in a subsequent PR.
> Extend search to allow for predicates

- README.md
- demos/full_table.jsx
- lib/search.jsx
The point here is to decouple the search component from the table component. `formatter` may not have always been the correct thing to use, especially if the developer decided to stick in extra markup.
I'm envisioning that the current `formatter` is going to get collapsed into `cell` (or some better named field). This will consist of a pipeline of transforms represented by an ordered list of functions.
> Add a transform field for search on column definition

- README.md
- __tests__/search-test.js
- demos/full_table.jsx
- lib/formatters/index.js
- lib/formatters/lowercase.js
- lib/search.jsx
Here are a list of changes that happened:
- changed highlighting logic so that it'll highlight any instance
- There's some annoyance here since the highlighter is currently coupled to logic inside the search
- switched default search option to lowercase and infix
- changed it so that Search component also does the filtering. This results in `onSearch` returning `data`.
We may want to consider bumping the major version number since this change is definitely not backwards compatible.
> Move filtering into the Search component

- src/editors/input.jsx
While editing an input field (cell), if you erase all chars from it, it will reinitialize the value of the input field to one defined through the component props. The PR fixes the problem by using only the state when rendering and setting the state to the props value at first.
> Problem when erasing the whole content of the input

- src/table.js
- tests/table_test.js
Currently the table does not aggregate the following cell functions correctly:
```js
cell: [
function(v){return {value: v}},
function(v){return {value: v}}
]
```
By the end of [the reduction loop in table.js](https://github.com/bebraw/reactabular/blob/9d1a67397bd7ae6d0199fe26458ba7564f64360e/src/table.js#L66), the cell content is aggregated as below, which cannot be rendered by React at all. [This test case](https://github.com/bebraw/reactabular/pull/122/files#diff-b9a69566df421fcb64ebcdee2e10dac5) demonstrates a more realistic example.
```js
{value: {value: "the value of the cell"} }
```
This pull request fixes the issue illustrated above.
The logic of reduce callback is simplified by ensuring the reducer callback always invoked with its argument `v` being an object like `{value: ..., …
> Merges props & values of cell functions correctly

- src/table.js
- tests/table_test.js
I came across a bug: given the following setup, the table cells would not display correct value.
```js
// data:
[{someColumn: 42}]
// columns:
[{
property: 'someColumn',
cell: v => v-42
}]
// Expected: A cell that shows "0"
// Actual: A cell that shows "42"
```
The cause lies in L73 of [src/table.js](https://github.com/bebraw/reactabular/blob/1651375213d8fc654b5049740c91e934c0dc4bad/src/table.js#L73). If `val` is falsy (like `0` in this case), it won't get wrapped as `{value: val}`, and `merge()` in [L78](https://github.com/bebraw/reactabular/blob/1651375213d8fc654b5049740c91e934c0dc4bad/src/table.js#L78) would ignore all non-object arguments when merging.
L73 should be testing if `val` needs wrapping. Thus I've fixed this by checking if `val` is a plain object instead. Hope it makes …
> Fix “formatter shortcut” logic in cell function.

- src/table.js
- tests/table_test.js
When data contains nested objects, it is useful to display two columns with the same `property` settings, and provide a cell function that reads from the nested object (see [the test](https://github.com/bebraw/reactabular/commit/91d102d9c08760820c7e5dd4f6574b3895c9014d) for example)
However, currently `<Table>` 's `render()` is flawed. The bug may cause a column's calculation result leaked to another column, which leads to the columns that share the same `property` settings renders incorrectly.
This pull request addresses the data leakage among columns and thus fixes the bug.
> Fix a bug that cell functions may be skipped when two columns shares the same property

- src/table.js
while we want to merge the props it doesn't make sense to merge values, particularly when they are React elements. merging values that are React elements will generally lead to a browser hang / crash in non-trivial examples. this is easily observed by running the demo locally on v.0.11.1.
> don't attempt to merge table cell values

- docs/sorting_table.md
- package.json
- src/column_names.js
- src/search.js
- src/sort_column.js
- src/sort_columns.js
- src/table.js
Explicitly importing subfunctions of lodash in Reactabular dramatically reduces the final bundle size of one of my projects. This is my first, bumbling foray into the React / Webpack stack, so I might be doing other ridiculous things, but this seemed like a good place to start.
Also, lodash 4.0.0 [renamed sortByOrder to orderBy](https://github.com/lodash/lodash/wiki/Changelog#v400), so this fixes that up.
> Import specific lodash funcs instead of everything

- docs/sorting_table.md
- sort documentation is unclear.
- sort documentation has cruft (e.g. `pagination/query/etc` code) that distracts from the actual sorting content
- sort documentation, whilst accurate,  is hard to disambiguate between the many usages of the term `sort` (e.g. the imported sort function, the sort-related state, and the sorted content)
- provide a discrete outline for how to sort your table data
- vary terminology to prevent possible ambiguation
- remove cruft
thanks for the great lib!  respectfully, it took me too long to interpret exactly what was going on here.  i patched the existing docs such that someone can open, read from top to bottom, and have absolute clarity on how to get their data sorted. hopefully the change will be welcomed!  it may be able to view the file raw/rendered vs …
> clarify sort usage

- demos/App.jsx
- demos/column_filters.jsx
- demos/full_table.jsx
- demos/full_table_multiple_filters.jsx
- demos/main.css
- docs/searching_table.md
- src/search.js
This adds an example of how to add a filter for each individual column of data, as was requested in #114. Each filter is then applied to the data in succession so the data for each search call is the result of the previous call.
- Wired up the ColumnFilters demo component
- Moved the ColumnFilters component from the FullTable demo component to a new FullTableMultipleFilters component which demonstrates the functionality of this PR
- Added a method _searchMultiple_ that searches across columns, successively filtering the table data
> Example of filtering data using different filters for each column

- lib/post_install.js
- package.json
execSync is replaced with spawn, and the dependency sync-exec is dropped.
Also, `npm prune --production` is run after the transpilation, to remove
unecessary devDependencies.
> Resolve bug in lib/post_install.js for node 0.10.x

- src/search.js
Just a small fix – the search wasn't working for me when I had resolvers that used `cellData`.
> Use full resolver incantation

- docs/table/body.md
Removes a character remnant from the old non-markdown docs.
> docs - remove remnant lt character

- docs/examples/all-features.md
- packages/reactabular-search-columns/src/index.jsx
Few changes were made. The main problem is the key value of th which is based on the index. As a result, the textbox within th does not get updated even when columns and query props change.
There was another bug that got resolved with this. It is related to the filtering of data in the demo. Removing the filter from the query object in state while toggling the column fixed the issue.
> Fixed bug: Toggling column with filter set

- packages/reactabular-sticky/package.json
See this error when trying to update to Reactabular 6.0.0:
```
❯ npm i
kao@21.8.2 /Users/sapegin/izumi/kao
└─┬ reactabular@6.0.0
├── reactabular-highlight@6.0.0
├── reactabular-resizable@6.0.0
├─┬ reactabular-resolve@6.0.0
│ └── reactabular-utils@6.0.0
├── reactabular-search@6.0.0
├── reactabular-search-columns@6.0.0
├── reactabular-search-field@6.0.0
├── reactabular-select@6.0.0
├── reactabular-sort@6.0.0
├── reactabular-sticky@6.0.0
└── UNMET PEER DEPENDENCY reactabular-table@6.0.0
npm WARN reactabular-sticky@6.0.0 requires a peer of reactabular-table@^5.1.0 but none was installed.
```
> Update reactabular-table version in peerDependencies

- packages/reactabular-easy/src/table.jsx
EasyTable `onRow` accepts `row, { rowIndex, rowKey }` instead of `row, rowIndex` as per changed Table.
This effectively fixes `Uncaught TypeError: Cannot read property Id of undefined` on row click in the Easy Version example.
> fix(easy) -`onRow` accepts `row, { rowIndex, rowKey }` per `table` breaking change

- packages/reactabular-sticky/src/body.js
I'm using external implementation of scroll bar and it's impossible to hide the tbody scroll bar.
> Allow overriding overflow for sticky table

- packages/reactabular-table/__tests__/resolve_row_key_test.js
- packages/reactabular-table/src/resolve-row-key.js
Check using Object.hasOwnProperty would warn erroneously
for valid object with getters, for example Immutable records.
> Fix false negative rowkey check.

- packages/reactabular-virtualized/README.md
- packages/reactabular-virtualized/src/body.js
height will be used if defined, or else fallback to style.maxHeight
tested by applying below patch and `npm run start`,
```diff
diff --git a/docs/drag-and-drop/with-virtualization.md b/docs/drag-and-drop/with-virtualization.md
index 46c3f4c..872881e 100644
--- a/docs/drag-and-drop/with-virtualization.md
+++ b/docs/drag-and-drop/with-virtualization.md
@@ -104,6 +104,7 @@ class VirtualizedTable extends React.Component {
super(props);
this.state = {
+      myHeight: 400,
rows,
columns
};
@@ -118,9 +119,17 @@ class VirtualizedTable extends React.Component {
// We have refs now. Force update to get those to Header/Body.
this.forceUpdate();
}
+  
+  clickMe() {
+     this.setState({
+      myHeight: this.state.myHeight===400? 200:400
+     })
+  }
+
render() {
return (
<div>
+        <button …
```
> virtualized can use props.style.maxHeight, #276

- packages/reactabular-virtualized/README.md
Adds a piece of less/sass stylesheet taken from an SO answer regarding scrollable table bodies. May not be perfect for everybody, but should serve as a good jumping-off point for most.
Feel free to flesh out more or to cut away :)
> Add section on relative widths

- packages/reactabular-dnd/src/draggable-row.js
Problem
---
Currently, this creates a new component "type" for each render. This causes React's reconciliation algorithm to re-render the entire row when cell contents change.
This isn't ideal for controlled components, like `<input>`s, because they will lose focus with each keypress.
Solution
---
Define the component class once and reuse it. I think this is equivalent—please let me know if I'm missing anything! :)
> draggable-row: don't create new component type

- package.json
The previous version seems to have used React.PropTypes, so corresponding warnings were output during test runs. To remove these warnings and have a smooth transition to React 16, I have upgraded the Jest version.
> Bumped Jest version to 19.0.2

- CONTRIBUTORS.md
- packages/reactabular-resizable/README.md
- packages/reactabular-resizable/__tests__/helper_test.js
- packages/reactabular-resizable/src/helper.js
I wrote a issue about resizing. 
I found bug that resizing table with nested columns, Resizing feature doesn't work. 
because resizing helper could detect only first depth column, except children.
In my code, There are `leafIndex` variable. leaf index is to distinguish either a column is leaf or not.
Thanks.
> #307 fix resizing feature in order to support resizing of nested columns

- CONTRIBUTORS.md
- packages/reactabular-virtualized/src/__tests__/prop_type_validation.js
- packages/reactabular-virtualized/src/body.js
#277 introduced the ability to use `style.maxHeight` instead of `height` but the propTypes are still producing a warning when the `height` prop is not present.
> fix virtualization propType warning

- docs/examples/header-body-aligned.md
- docs/examples/index.js
Add an example on creating a third party component `HorizontalScrollBar` to fix #282 and #259 
Since it's third party component, it has no impact on existing reactabular code.
> Add example to align sticky header and body

- packages/reactabular-virtualized/src/body.js
#319 
Adds clearTimeout() to reactabular-virtualized to avoid warning on calling forceUpdate and setState on unmounted components.
> Add missing clearTimeout

- package-lock.json
- package.json
The new version of tabular uses React 16.x whereas the old one uses 15.x.
> chore: Update treetabular

- packages/reactabular-table/README.md
This just caught me as someone new to the library.  I did a quick edit using the GitHub editor.  This is a quick docs-only fix, so I'm not sure if the contribution guidelines all still apply.
thanks!
> Fix example import statement for reactabular-table

- packages/reactabular-virtualized/src/body.js
- packages/reactabular-virtualized/src/calculate-rows.js
Fixed an issue with Server Side Rendering. Virtualized logging can still be enabled in the browser. Can't see any problematic side effects.
> Check if window is defined before checking LOG_VIRTUALIZED

- docs/examples/all-features.md
In the example code, there is a typo in the import section.  "transforms" from lodash should be singular, I have changed it to "transform".
> fix typo in lodash import in examples/add-features.md

- CONTRIBUTORS.md
- packages/reactabular-virtualized/README.md
- packages/reactabular-virtualized/src/__tests__/body_test.js
- packages/reactabular-virtualized/src/__tests__/calculate-rows_test.js
- packages/reactabular-virtualized/src/__tests__/prop_type_validation.js
- packages/reactabular-virtualized/src/body.js
- packages/reactabular-virtualized/src/calculate-rows.js
Our designers want to be able to have tables scroll with the surrounding content in the page and have multiple tables in a list. This is tricky because some of the tables have thousands of entries and the designers are very against pagination. A natural solution was virtualization. So I added the ability to specify a container to use for scrolling and use that instead of creating a scrolling table inside of the component.
I tested for backward compatibility and it shouldn't break any existing tables, but an extra set of eyes on that is always a good thing 😄 .
> Added option to use a container for the scrolling in virtualization

- package-lock.json
- packages/reactabular-virtualized/src/__tests__/body_test.js
- packages/reactabular-virtualized/src/body.js
I have no idea why I didn't include this in the original feature but the virtualization inside a container did not account for the size of the thead so the items were cutting off a little early as they scroll. This can apparently cause some weird flickering if you get the page to just the right scroll.
> Fix virtualized scrolling in container to account for thead height

- packages/reactabular-resizable/src/helper.js
Currently, nested columns do not have a width.
Changed to have width by changing class name.
> fix(resizable): get class name

- package.json
- webpack.config.babel.js
Currently the docs dont work in ie11 - both locally and live.
You just get a white screen with console error: SCRIPT438: Object doesn't support property or method 'assign'
I've added the babel-polyfill now to fix this.
> add babel-polyfill so the docs run in IE11

- packages/reactabular-virtualized/README.md
In Edge the first table in the virtualized page renders incorrectly (ie the height is not constrained)
Fixed now:
> Fix the Virtualized example when running in Edge
