README.md, __tests__/predicates/infix-test.js, __tests__/predicates/prefix-test.js, demos/full_table.jsx, lib/formatters/highlight.js, lib/formatters/index.js, lib/predicates/infix.js, lib/predicates/prefix.js, lib/search.jsx
Fixes #36.
Also fixes a bug before where the highlighter occurs regardless of selected column on the search component.
=> Refactor highlighter into Search component

lib/search.jsx
=> Remove the use of refs

src/formatters/highlight.js
=> Add key to highlight spans

README.md
Without the columns props the table will not render the data.
=> Fix search example

src/editors/input.js
It was a bit annoying having to click two times in order to edit a cell so... you know! :smile:
=> Input editor autofocus

src/search.js
This makes it easier to simply extend the existing Search class, to build your own custom implementations/design.
This is a follow up to #67
=> Search: extract getOptions to own method

lib/post_install.js, package.json
=> Support Node 0.10 again

docs/table_definition.md
related to https://github.com/bebraw/reactabular/commit/903d2fa0de323e6418ee870c3c21ab82ffd68567
=> replace className with headerClass

docs/sorting_table.md
=> correct usage from props.header to props.columnNames

packages/reactabular-sort/README.md, packages/reactabular-sort/src/by_columns_prioritize_last_sorted.js, packages/reactabular-sort/src/index.js, packages/reactabular-sort/tests/by_columns_prioritize_last_sorted_test.js
Here you go – I'll gladly take any other name if you can think of one. :)
=> Add sort.byColumnsPrioritizeLastSorted

CONTRIBUTING.md
Corrected code snippet to correctly use GitHub notation.
=> Corrected code snippet to correctly use GitHub notation

webpack.config.babel.js
Most of the pages are at least readable ;-)
Catalog already supports responsiveness.
=> Enable mobile mode for HtmlWebpackPlugin

packages/reactabular-search/src/_column_matches.js
- Fixed the columnMatches function, where an empty column property caused wrong search results.
- Performance improvement by making separate functions for default parameters.
=> Filtering fix

packages/reactabular-dnd/README.md
Was broken since 7.0.0 I suppose.
=> Fix dnd example

README.md
=> Add a testimonial

packages/reactabular-virtualized/src/body.js
If the height increases the rows need to be calculated to fill the new height.
=> virtualized - Calculate rows when height changes

docs/examples/index.js, docs/examples/styled-components.md, package.json
Hi,
as discussed, I have added a minimal example on how to combine [styled components](https://styled-components.com/) with the overriding of default elements as provided by reactabular. I created a documentation page, but did not include the page in the documentation index. Feel free to comment.
=> Example for overriding default element with styled component

packages/reactabular-sticky/README.md, packages/reactabular-table/README.md
import statements are biffed
patch
it's been a long while since i've been to reactabular.  looks like a lot has changed!  time to dig in
=> docs(README): patch README import statements

docs/examples/fixed-columns.md, docs/examples/index.js
=> Add example of table with fixed columns

packages/virtualized/src/calculate-rows.js
=> Fixed startIndex undefined

CONTRIBUTORS.md, packages/reactabular-dnd/src/draggable-row.js
=> Added Hovered Class to Hovered Row

CONTRIBUTORS.md, packages/reactabular-virtualized/src/body.js
Hi! Thanks for your framework!
This is a little fix for this
=> Fix scrollTo at reactabular-virtualized

docs/examples/styled-components.md
Documentation on how to pass the property `isTinyNumber` created in cell transform to styled component
=> doc on combining styled-components and transforms

docs/drag-and-drop/with-virtualization.md
Change deprecated components prop to renderers
=> Minor readme update
